### PR TITLE
Load gpg signature data asynchronously.

### PR DESCRIPTION
**Pull request by jbialobr**
I believe you were misled by the InvokeAsync method name.
If your intention was to invoke this in background, then this PR corrects it.

### CODE REVIEW

**Comment by RussKie** [comment]
we could also update the signature to use proper `async`

**Comment by RussKie** [comment]
https://github.com/gpongelli/gitextensions/pull/6

**Comment by jbialobr** [comment]
>we could also update the signature to use proper async

Good point.

**Comment by RussKie** [comment]
I haven't had a chance to run it, but it should work

**Comment by jbialobr** [comment]
It works, though it is not equivalent to this PR. We don't have to wait for the first task to be able to invoke the second one. They should go in parallel. For most cases the tagsignature is computed immediately and returns NoTag without executing git command.
See https://github.com/RussKie/gitextensions/pull/5

**Comment by RussKie** [comment]
Yes, you're absolutely right
I rushed it, had to get off the train. Didn't have time to run it....

**Pull request closed without merging**
